import { IStepperData, IWorkData } from "./types";

export const workData: IWorkData[] = [
  {
    image: '/joyapp-logo.png',
    company: 'Pepsi',
    projectType: 'App',
    cardDescription:
      'The Joy App by PepsiCo offers seamless access to PepsiCo products, promotions, and rewards, aiming to enhance customer engagement and satisfaction.',
    isBlurred: false,
    startDate: 'september 2023',
    endDate: 'present',
    description:
      'Do incididunt culpa laborum in amet culpa ut cillum exercitation qui duis qui irure. Aute commodo veniam enim voluptate id reprehenderit deserunt eiusmod. Dolore tempor aute tempor aliquip laborum pariatur sint. Et eu cupidatat aute aliqua dolor sit reprehenderit qui cupidatat enim voluptate magna est officia. Ullamco Lorem ea ad officia proident velit qui elit exercitation.',
    whatIHaveDone:
      'Implemented Firebase remote config for dynamic updates and personalized experiences. Added deep links and events to support marketing campaigns and user redirection. Enhanced UX/UI across all screens for a cohesive interface. Addressed bugs and improved app stability using Firebase Crashlytics.',
    workScheme: 'remote',
    jobTitle: 'Software Engineer Assoc Manager',
    stack: ['Dart', 'Flutter', 'Firebase', 'Appsflyer'],
    projectName: 'Joy App',
    images: [],
  },
  {
    image: '/walmart-logo.svg',
    company: 'Walmart',
    projectType: 'App',
    cardDescription:
      'Global retail giant offering a wide range of products including groceries, household goods, electronics, and apparel at competitive prices through its extensive network of stores and online platforms.',
    isBlurred: false,
    startDate: 'august 2023',
    endDate: 'january 2024',
    description: '',
    whatIHaveDone: '',
    workScheme: 'remote',
    jobTitle: 'Freelance Software Engineer UP',
    stack: ['TypeScript', 'React Native', 'React Native CLI', 'micro-frontends'],
    projectName: 'Me@Walmart International',
    images: [],
  },
  {
    image: '/gulf-logo.png',
    company: 'Gulf',
    projectType: 'Web',
    cardDescription:
      'Gulf is a multinational company specializing in energy, petroleum refining, and related services. It operates across various sectors, including oil exploration, production, refining, and distribution.',
    isBlurred: false,
    startDate: 'june 2023',
    endDate: 'august 2023',
    description: '',
    whatIHaveDone: '',
    workScheme: 'remote',
    jobTitle: 'Freelance Lead Developer',
    stack: ['TypeScript', 'Angular', 'NodeJs', 'TypeORM'],
    projectName: 'Gulf',
    images: [],
  },
  {
    image: '/pentalog-logo.webp',
    company: 'Pentalog',
    projectType: 'Web',
    cardDescription:
      'Pentalog is a global digital services platform offering end-to-end IT solutions, including software development, consulting, and digital transformation services.',
    isBlurred: false,
    startDate: 'august 2021',
    endDate: 'august 2023',
    description: '',
    whatIHaveDone: '',
    workScheme: 'remote',
    jobTitle: 'Software Engineer',
    stack: ['TypeScript', 'React', 'Ant Design', 'GraphQL'],
    projectName: 'Noodle',
    images: [],
  },
  {
    image: '/asistensi-logo.svg',
    company: 'Asistensi',
    projectType: 'App',
    cardDescription:
      'Innovative platform connecting users with personalized, on-demand assistance services such as ambulance, medicine delivery and online medical assistance',
    isBlurred: false,
    startDate: 'june 2022',
    endDate: 'april 2023',
    description: '',
    whatIHaveDone: '',
    workScheme: 'remote',
    jobTitle: 'Mobile Developer',
    stack: ['TypeScript', 'React Native', 'Tailwind CSS'],
    projectName: 'Joy App',
    images: [],
  },
  {
    image: '/kavak-logo.svg',
    company: 'Kavak',
    projectType: 'App',
    cardDescription:
      'Premier platform for transparent, hassle-free buying and selling of pre-owned cars. Trusted by individuals and dealerships for its reliability and streamlined experience.',
    isBlurred: false,
    startDate: 'august 2021',
    endDate: 'june 2022',
    description: '',
    whatIHaveDone: '',
    workScheme: 'remote',
    jobTitle: 'Software Engineer Assoc Manager',
    stack: ['TypeScript', 'GraphQL', 'Angular', 'DataDog'],
    projectName: 'Joy App',
    images: [],
  },
  {
    image: '/am-logo.jpeg',
    company: 'Advanced Mankind',
    projectType: 'App',
    cardDescription:
      'AM offer expert guidance for optimizing technology infrastructure and processes, including strategic planning, system design, software development, and project management.',
    isBlurred: false,
    startDate: 'july 2020',
    endDate: 'january 2022',
    description: '',
    whatIHaveDone: '',
    workScheme: 'remote',
    jobTitle: 'FullStack Developer',
    stack: [
      'TypeScript',
      'JavaScript',
      'Dart',
      'Flutter',
      'Angular',
      'HTML',
      'CSS',
      'SASS',
      'React Native',
      'React',
      'MapBox',
      'NodeJS',
      'MySQL',
    ],
    projectName: 'Xybrid',
    images: [],
  },
  {
    image: '/axend-logo.png',
    company: 'Axend',
    projectType: 'Web',
    cardDescription:
      'Axend is a platform dedicated to fostering growth for individuals and businesses through investments.',
    isBlurred: false,
    startDate: 'february 2019',
    endDate: 'february 2021',
    description: 'descripción chida y mamalona',
    whatIHaveDone: '',
    workScheme: 'remote',
    jobTitle: 'Chief Technology Officer & Full Stack Developer',
    stack: ['JavaScript', 'NuxtJs', 'VueJs', 'NodeJs', 'Express', 'Google Cloud Platform'],
    projectName: 'Axend webapp',
    images: [],
  },
];

export const stepperData: IStepperData[] = [
  {
    date: 'September 15 2023',
    description: 'Started working with PepsiCo for the Joy App',
    icon: '/work.svg',
  },
  {
    date: 'August 31 2023',
    description: "Finished Gulf's project",
    icon: '/work.svg',
  },
  {
    date: 'June 1 2023',
    description: 'Started my first freelance project with Gulf',
    icon: '/work.svg',
  },
  {
    date: 'February 28 2023',
    description: 'Finished all my subjects as a Computer Engineer',
    icon: '/school.svg',
  },
  {
    date: 'August 15 2022',
    description: 'Belog to the top 5% of programmers at Pentalog (2021-2022)',
    icon: '/award.svg',
  },
  {
    date: 'February 1 2021',
    description: 'Started working as a Mobile Developer',
    icon: '/work.svg',
  },
  {
    date: 'February 1 2019',
    description: 'Started working as a Web Developer',
    icon: '/work.svg',
  },
  {
    date: 'December 12 2018',
    description: '3rd place at Local Hack Day by Github',
    icon: '/award.svg',
  },
];